### ISSUE TITLE
Error in load("~/BnaSNPDB/data/Other_data/Ref.gene.anno.RData")

### ISSUE THREAD

**Issue by PengGYing** [YTLogos/BnaSNPDB#67]
Error in load("~/BnaSNPDB/data/Other_data/Ref.gene.anno.RData") : 
  復原文件幻数出错(文件可能有损坏)-- 没有载入任何数据（Error restoring magic number of file (file may be corrupted) - no data loaded）

**Comment by YTLogos** [comment]
> Error in load("~/BnaSNPDB/data/Other_data/Ref.gene.anno.RData") :
> 復原文件幻数出错(文件可能有损坏)-- 没有载入任何数据（Error restoring magic number of file (file may be corrupted) - no data loaded）

我更新了数据，现在应该可以使用了，我猜测是由操作系统引起的，在我自己的电脑上是可以运行的，然后git clone之后可能导致数据格式出现错误，希望有用！

**Comment by PengGYing** [comment]
> > Error in load("~/BnaSNPDB/data/Other_data/Ref.gene.anno.RData") :
> > 可能恢复文件幻数出错(文件有损坏)-- 没有载入任何数据（Error recovery magic number of file (file可能已损坏） - 未加载数据）
> 
> 我更新了数据，现在应该使用了，我自己是由自带的，在我的电脑上是可以运行的，然后git克隆可能会导致数据格式出现错误，希望专业！

我得到了另外一个错误提示，在Ubuntu20.04上，R版本4.1.0， 提示为file ‘Ref.gene.anno.RData’ has magic number 'versi' Use of save versions prior to 2 is deprecated，我不确定是不是R版本问题。此问题在win10，R4.1.0时未出现错误。其次，如果我想更改数据，采用其他基因数据，不知道作者能否写一个使用教程，谢谢。

**Comment by YTLogos** [comment]
@PengGYing 多平台运行是会出现很多兼容性问题，无法避免，因此我有将BnaSNPDB容器化，打包成了Docker文件，可以通过docker运行在任何操作系统上。如果想更改数据的话，无法提供一个详细的使用教程，因为这毕竟不是一个框架或者模板，但是如果你愿意花点时间，仔细阅读脚本，实际上还是很容易替换数据的！只要将各种数据以及信息对应好就行！
