### ISSUE TITLE
BnaGVD VCF header is missing

### ISSUE THREAD

**Issue by alartin** [YTLogos/BnaSNPDB#68]
Hi Tao,
There is no BnaGVD repo, so I posted the issue of BnaGVD here. I couldn't find any VCF header in the VCF files downloaded from BnaGVD, while it is important for the integrity of VCF file. Could you please provide the original VCF headers including the sample ids for samples columns? Thanks a lot!

**Comment by YTLogos** [comment]
[header.txt](https://github.com/YTLogos/BnaSNPDB/files/9372126/header.txt)

Hi @alartin, sorry for the later response. Here is the header. Don't hesitate to contact me if you have any other questions.
Best wishes,
Tao

**Comment by alartin** [comment]
> [header.txt](https://github.com/YTLogos/BnaSNPDB/files/9372126/header.txt)
> 
> Hi @alartin, sorry for the later response. Here is the header. Don't hesitate to contact me if you have any other questions. Best wishes, Tao
Hi Tao,
Thanks a lot!
